### PR TITLE
Add tests for GTDB taxa parser

### PR DESCRIPTION
**Pull request by MrCreosote**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Codecov seems to be going downhill lately. There's clearly not 113 new tested lines here, and when I go do the codecov page to see what's going on I get this:
image

**Comment by MrCreosote** [comment]
That and page loads are insanely slow

**Comment by MrCreosote** [comment]
Hmm, the ncbi parsers don't show up either even though they were merged into master https://app.codecov.io/gh/kbase/relation_engine_importers

**Review by scanon — APPROVED** [review]
LGTM

**Pull request merged**
